spring.application.name=arrgano
# JWT
app.jwtSecret=YourJwtSecretKeyHere
app.jwtExpirationInMs=86400000 # 24h

# MongoDB
pring.data.mongodb.uri=mongodb://localhost:27017/arrgano_db
spring.data.mongodb.auto-index-creation=true

# Security
spring.security.user.name=
spring.security.user.password=

jwt.secret=VotreCleSecreteSuperSecureAvecMinimum256Bits